services:
  backend:
    build:
      context: ./back_end/POS_Backend/POS_Backend
      dockerfile: Dockerfile
      container_name: pos-backend
    ports:
      - "7279:80"               
    restart: unless-stopped

  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
      container_name: pos-frontend
    ports:
      - "5173:80"               
    depends_on:
      - backend
    restart: unless-stopped